Repository codestates-seb/seb39_main_038, pull requests merged in 2022-10, with the labels that each got.

#162 feat: 장바구니 메뉴 리스트 atom Session Storage 상태관리 완성
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/DetailReview/index.js
  frontend/src/components/Receipt/index.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/FoodTruckSetting/styles.js
  frontend/src/store/atoms.js
  frontend/src/store/index.js
Labels: 📱 FE

#166 design: Review 컴포넌트 UI & CSS 구현 완료
  frontend/src/App.js
  frontend/src/components/DetailReview/index.js
  frontend/src/components/DetailReview/styles.js
  frontend/src/constants/route.js
  frontend/src/pages/FoodList/FoodTrucks/index.js
  frontend/src/pages/Review/index.js
  frontend/src/pages/Review/styles.js
  frontend/src/store/index.js
Labels: 📱 FE, ✨ UI/UX, ⭐⭐ 중요도

#168 feat: review, comment, store CRUD
  src/main/java/com/main_39/Spring/advice/ErrorResponse.java
  src/main/java/com/main_39/Spring/comment/controller/CommentController.java
  src/main/java/com/main_39/Spring/comment/dto/CommentPatchDto.java
  src/main/java/com/main_39/Spring/comment/dto/CommentPostDto.java
  src/main/java/com/main_39/Spring/comment/dto/CommentResponseDto.java
  src/main/java/com/main_39/Spring/comment/entity/Comment.java
  src/main/java/com/main_39/Spring/comment/mapper/CommentMapper.java
  src/main/java/com/main_39/Spring/comment/repository/CommentRepository.java
  src/main/java/com/main_39/Spring/comment/service/CommentService.java
  src/main/java/com/main_39/Spring/exception/ExceptionCode.java
  src/main/java/com/main_39/Spring/member/mapper/MemberMapper.java
  src/main/java/com/main_39/Spring/member/service/MemberService.java
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/dto/ReviewPostDto.java
  src/main/java/com/main_39/Spring/review/dto/ReviewResponseDto.java
  src/main/java/com/main_39/Spring/review/dto/ReviewsResponseDto.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/review/entity/ReviewSeller.java
  src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
  src/main/java/com/main_39/Spring/review/repository/ReviewRepository.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
  src/main/java/com/main_39/Spring/store/dto/StoreListResponseDto.java
  src/main/java/com/main_39/Spring/store/dto/StoreMenuPostDto.java
  src/main/java/com/main_39/Spring/store/dto/StoreMenuResponseDto.java
  src/main/java/com/main_39/Spring/store/dto/StorePatchDto.java
  src/main/java/com/main_39/Spring/store/dto/StorePostDto.java
  src/main/java/com/main_39/Spring/store/dto/StoreResponseDto.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
  src/main/java/com/main_39/Spring/store/mapper/StoreMapper.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🖥 BE, ⚙ 설정

#169 feat: review, store CRUD 추가
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/dto/ReviewPostDto.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정

#179 feat: 장바구니 UI 작업
  frontend/.eslintrc.json
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/DetailInfo/index.js
  frontend/src/components/DetailReview/index.js
  frontend/src/components/Receipt/index.js
  frontend/src/components/ReceiptList/index.js
  frontend/src/components/ReceiptList/styles.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/FoodList/FoodDetail/styles.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/FoodTruckSetting/styles.js
  frontend/src/store/atoms.js
Labels: 📱 FE, ✨ UI/UX

#178 refactor: 카카오 <-> 주문 매핑, 메뉴 응답 dto에 메뉴 소개 추가
  src/main/java/com/main_39/Spring/member/entity/Kakao.java
  src/main/java/com/main_39/Spring/menu/MenuMapper.java
  src/main/java/com/main_39/Spring/menu/controller/MenuController.java
  src/main/java/com/main_39/Spring/menu/dto/MenuResponse.java
  src/main/java/com/main_39/Spring/menu/entity/Menu.java
  src/main/java/com/main_39/Spring/menu/service/MenuService.java
  src/main/java/com/main_39/Spring/order/controller/OrderController.java
  src/main/java/com/main_39/Spring/order/dto/OrderDetailResponse.java
  src/main/java/com/main_39/Spring/order/dto/OrderMenuRequest.java
  src/main/java/com/main_39/Spring/order/dto/OrderMenuResponse.java
  src/main/java/com/main_39/Spring/order/dto/OrderPostRequestDto.java
  src/main/java/com/main_39/Spring/order/dto/OrderRequest.java
  src/main/java/com/main_39/Spring/order/dto/OrderResponse.java
  src/main/java/com/main_39/Spring/order/dto/OrdersResponse.java
  src/main/java/com/main_39/Spring/order/entity/Order.java
  src/main/java/com/main_39/Spring/order/mapper/OrderMapper.java
  src/main/java/com/main_39/Spring/order/service/OrderService.java
Labels: 🖥 BE, 🔨 리펙토링

#181 feat: 장바구니 기능 구현 완료
  frontend/src/App.js
  frontend/src/components/CustomModal/FoodModal/index.js
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/LocalNav/styles.js
  frontend/src/components/Receipt/index.js
  frontend/src/components/ReceiptList/index.js
  frontend/src/components/Spinner/index.js
  frontend/src/components/Spinner/styles.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useFoodDetail.js
  frontend/src/hooks/useMyPage.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/FoodList/FoodDetail/styles.js
  frontend/src/pages/FoodList/FoodTrucks/index.js
  frontend/src/pages/MyPage/index.js
  frontend/src/store/atoms.js
  server/app.js
Labels: 📱 FE, ⭐⭐ 중요도

#185 feat: review, store CRUD 추가
  src/main/java/com/main_39/Spring/comment/controller/CommentController.java
  src/main/java/com/main_39/Spring/comment/dto/CommentPostDto.java
  src/main/java/com/main_39/Spring/comment/dto/CommentResponseDto.java
  src/main/java/com/main_39/Spring/comment/entity/Comment.java
  src/main/java/com/main_39/Spring/comment/service/CommentService.java
  src/main/java/com/main_39/Spring/member/mapper/MemberMapper.java
  src/main/java/com/main_39/Spring/review/dto/ReviewStoreResponseDto.java
  src/main/java/com/main_39/Spring/review/dto/ReviewsResponseDto.java
  src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
  src/main/java/com/main_39/Spring/store/dto/StoreResponseDto.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정

#186 feat : local entity 수정
  src/main/java/com/main_39/Spring/member/entity/Local.java
Labels: 🖥 BE, ⚙ 설정

#190 fix: review CRUD 수정
  src/main/java/com/main_39/Spring/review/dto/ReviewsResponseDto.java
  src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
Labels: 🖥 BE, ⚙ 설정

#191 feat: 결제 기능 추가 완료
  frontend/public/index.html
  frontend/src/components/CustomModal/FoodModal/index.js
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/Receipt/index.js
  frontend/src/components/Receipt/styles.js
  frontend/src/components/ReceiptList/index.js
  frontend/src/components/ReceiptList/styles.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useDetailFoodList.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/FoodList/FoodDetail/styles.js
  frontend/src/pages/Order/index.js
  frontend/src/pages/Order/styles.js
  server/app.js
  server/data/index.js
  server/data/menuList.js
Labels: 📱 FE, ✨ UI/UX, ⭐ 중요도

#192 fix : reviewMapper 수정
  src/main/java/com/main_39/Spring/review/dto/ReviewsResponseDto.java
  src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
Labels: 🖥 BE, ⚙ 설정

#193 feat : crud test
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
  src/main/java/com/main_39/Spring/store/dto/StorePostDto.java
Labels: 🖥 BE, ⚙ 설정

#194 feat: crud test 내용 복원
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
  src/main/java/com/main_39/Spring/store/dto/StorePostDto.java
Labels: 🖥 BE, ⚙ 설정

#195 refactor: 주문요청사항 추가, 주문 리스트, 상세 주문 응답 수정
  src/main/java/com/main_39/Spring/order/controller/OrderController.java
  src/main/java/com/main_39/Spring/order/dto/OrderDetailResponse.java
  src/main/java/com/main_39/Spring/order/dto/OrderRequest.java
  src/main/java/com/main_39/Spring/order/dto/OrderResponse.java
  src/main/java/com/main_39/Spring/order/dto/OrdersResponse.java
  src/main/java/com/main_39/Spring/order/entity/Order.java
  src/main/java/com/main_39/Spring/order/mapper/OrderMapper.java
Labels: 🖥 BE, 🔨 리펙토링

#198 feat: review, store, comment CRUD 추가
  src/main/java/com/main_39/Spring/comment/controller/CommentController.java
  src/main/java/com/main_39/Spring/comment/entity/Comment.java
  src/main/java/com/main_39/Spring/comment/mapper/CommentMapper.java
  src/main/java/com/main_39/Spring/comment/repository/CommentRepository.java
  src/main/java/com/main_39/Spring/comment/service/CommentService.java
  src/main/java/com/main_39/Spring/menu/controller/MenuController.java
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/dto/ReviewPostDto.java
  src/main/java/com/main_39/Spring/review/dto/ReviewResponseDto.java
  src/main/java/com/main_39/Spring/review/dto/ReviewStoreResponseDto.java
  src/main/java/com/main_39/Spring/review/dto/ReviewsResponseDto.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
  src/main/java/com/main_39/Spring/review/repository/ReviewRepository.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
  src/main/java/com/main_39/Spring/store/dto/StoreListResponseDto.java
  src/main/java/com/main_39/Spring/store/dto/StoreMenuPostDto.java
  src/main/java/com/main_39/Spring/store/dto/StoreMenuResponseDto.java
  src/main/java/com/main_39/Spring/store/dto/StoreResponseDto.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
  src/main/java/com/main_39/Spring/store/mapper/StoreMapper.java
  src/main/java/com/main_39/Spring/store/repository/StoreRepository.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🖥 BE, ⚙ 설정

#199 feat: storeType별 목록 불러오기 추가
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
  src/main/java/com/main_39/Spring/store/repository/StoreRepository.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🖥 BE, ⚙ 설정

#204 refactor: 주문 기능 메뉴 응답에 가게id 추가
  src/main/java/com/main_39/Spring/order/dto/OrderMenuResponse.java
  src/main/java/com/main_39/Spring/order/mapper/OrderMapper.java
Labels: 🖥 BE, 🔨 리펙토링

#205 feat: 결제 SDK 연동 완료
  frontend/src/components/CustomModal/FoodModal/index.js
  frontend/src/components/CustomModal/Modal/styles.js
  frontend/src/components/LocalNav/styles.js
  frontend/src/components/Receipt/index.js
  frontend/src/constants/api.js
  frontend/src/hooks/index.js
  frontend/src/hooks/usePay.js
  frontend/src/pages/Order/index.js
  frontend/src/utils/date.js
  frontend/src/utils/index.js
  frontend/src/utils/randomRange.js
Labels: 📱 FE, ⭐⭐ 중요도

#207 refactor: 주문 기능 메뉴 응답에 가게명 추가
  src/main/java/com/main_39/Spring/order/dto/OrderMenuResponse.java
  src/main/java/com/main_39/Spring/order/mapper/OrderMapper.java
Labels: 🖥 BE, 🔨 리펙토링

#208 feat: store 중복 예외처리 추가
  src/main/java/com/main_39/Spring/exception/ExceptionCode.java
  src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
  src/main/java/com/main_39/Spring/store/repository/StoreRepository.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🖥 BE, ⚙ 설정

#209 feat: store update 수정
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🖥 BE, ⚙ 설정

#216 fix: review CRUD 수정
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
Labels: 🖥 BE, 🔨 리펙토링, 🙋‍♂️ 리뷰 관련 작업

#217 feat: github actions TEST
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
Labels: 🖥 BE, ⚙ 설정

#218 fix: review CRUD 수정
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/dto/ReviewPostDto.java
  src/main/java/com/main_39/Spring/review/dto/ReviewResponseDto.java
  src/main/java/com/main_39/Spring/review/dto/ReviewsResponseDto.java
  src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#219 feat: 최종 테스트 중
  frontend/src/App.js
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/DetailInfo/index.js
  frontend/src/constants/route.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/FoodTruckSetting/styles.js
  frontend/src/pages/MyPage/index.js
Labels: 📱 FE

#220 fix: API 인터페이스 수정 완료
  frontend/src/components/CustomModal/OrderModal/index.js
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/DetailReview/index.js
  frontend/src/components/FoodTruck/index.js
  frontend/src/components/Receipt/index.js
  frontend/src/constants/api.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useOrderList.js
  frontend/src/hooks/usePay.js
  frontend/src/hooks/useReview.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/MyPage/index.js
  frontend/src/pages/MyPage/styles.js
  frontend/src/pages/Review/AskReview.js
  frontend/src/pages/Review/UpdateReview.js
  frontend/src/pages/Review/index.js
  frontend/src/store/atoms.js
  frontend/webpack.config.js
  server/app.js
  server/data/foodReview.js
  server/data/index.js
Labels: ⭐⭐ 중요도, 🍽 주문 관련 작업, 💵 결제 관련 작업

#221 refactor: 주문 기능 카카오 주석 해제
  src/main/java/com/main_39/Spring/order/controller/OrderController.java
Labels: 🖥 BE, ⚙ 설정

#222 feat : comment update 추가
  src/main/java/com/main_39/Spring/comment/controller/CommentController.java
  src/main/java/com/main_39/Spring/comment/dto/CommentPatchDto.java
  src/main/java/com/main_39/Spring/comment/mapper/CommentMapper.java
  src/main/java/com/main_39/Spring/comment/service/CommentService.java
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/dto/ReviewResponseDto.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#234 feat: 로컬 회원으로도 주문 가능하게 추가
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/order/controller/OrderController.java
  src/main/java/com/main_39/Spring/order/entity/Order.java
Labels: 🖥 BE, ⚙ 설정

#245 fix: review Local 작성 수정
  src/main/java/com/main_39/Spring/member/entity/Kakao.java
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/member/entity/Users.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#246 fix: order 수정
  src/main/java/com/main_39/Spring/order/entity/Order.java
Labels: 🖥 BE, ⚙ 설정

#247 fix: LAZY 설정
  src/main/java/com/main_39/Spring/member/entity/Local.java
Labels: 🖥 BE, ⚙ 설정

#248 fix: EAGER 복원
  src/main/java/com/main_39/Spring/member/entity/Local.java
Labels: 🖥 BE, ⚙ 설정

#249 fix: LAZY 설정
  src/main/java/com/main_39/Spring/member/entity/Local.java
Labels: 🖥 BE, ⚙ 설정

#250 fix: FetchType 제거
  src/main/java/com/main_39/Spring/member/entity/Kakao.java
  src/main/java/com/main_39/Spring/member/entity/Local.java
Labels: 🖥 BE, ⚙ 설정

#251 test: fetch test
  src/main/java/com/main_39/Spring/member/entity/Kakao.java
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/order/entity/Order.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
Labels: 🖥 BE, ⚙ 설정

#252 fix: fetchtype 수정
  src/main/java/com/main_39/Spring/member/entity/Local.java
Labels: 🖥 BE, ⚙ 설정

#253 fix: @EntityGraph 추가
  src/main/java/com/main_39/Spring/member/repository/LocalRepository.java
Labels: 🖥 BE, ⚙ 설정

#255 feat: fetchType 수정
  src/main/java/com/main_39/Spring/member/entity/Local.java
Labels: 🖥 BE, ⚙ 설정

#257 fix: @LazyCollection 추가
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정

#258 fix: @LazyCollection 추가
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정

#259 fix: 리뷰 등록 수정
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
Labels: 🖥 BE, ⚙ 설정

#264 fix: 메뉴 삭제 기능 fix
  src/main/java/com/main_39/Spring/menu/controller/MenuController.java
  src/main/java/com/main_39/Spring/menu/service/MenuService.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🕷 버그, 🖥 BE

#269 fix: comment 삭제 수정
  src/main/java/com/main_39/Spring/comment/service/CommentService.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#270 fix: comment 삭제 수정
  src/main/java/com/main_39/Spring/comment/service/CommentService.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#271 fix: review 수정
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#273 fix: cascade 제거
  src/main/java/com/main_39/Spring/comment/entity/Comment.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#275 fix: review 수정
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#276 fix: cascade 추가
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#277 fix: cascade 삭제
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정, 🔨 리펙토링

#278 fix: review findAll 제거
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#279 fix : store 주석처리
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🖥 BE, ⚙ 설정

#280 fix: storeRepository query 추가
  src/main/java/com/main_39/Spring/comment/entity/Comment.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
  src/main/java/com/main_39/Spring/store/repository/StoreRepository.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🖥 BE, ⚙ 설정

#281 fix: storerepository query 제거
  src/main/java/com/main_39/Spring/store/repository/StoreRepository.java
Labels: 🖥 BE, ⚙ 설정

#283 feat: 기능 최종본
  frontend/babel.config.js
  frontend/src/App.js
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/DetailInfo/styles.js
  frontend/src/components/Hoc/index.js
  frontend/src/constants/api.js
  frontend/src/constants/route.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/FoodTruckSetting/styles.js
Labels: 🕷 버그, 📱 FE, ⚙ 설정

#284 feat: 답변 & 질문 예외처리 완료
  README.md
  frontend/src/components/Answer/index.js
  frontend/src/components/Answer/styles.js
  frontend/src/components/CustomModal/FoodModal/index.js
  frontend/src/components/DetailReview/index.js
  frontend/src/components/GlobalNav/index.js
  frontend/src/components/Receipt/index.js
  frontend/src/components/ReceiptList/index.js
  frontend/src/constants/api.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useAnswer.js
  frontend/src/hooks/useReview.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Login/ProviderLogin/index.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/MyPage/index.js
  frontend/src/pages/Order/index.js
  frontend/src/pages/Review/index.js
  frontend/src/store/atoms.js
Labels: 📱 FE, ⚙ 설정, ⭐⭐ 중요도

#286 fix: 무한루프 수정 완료
  frontend/src/components/DetailFoodList/index.js
  frontend/src/constants/api.js
  frontend/src/constants/route.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/Home/index.js
  frontend/src/store/atoms.js
Labels: 🕷 버그, 📱 FE, ⚙ 설정

#287 fix: 무한 루프 수정 완료
  frontend/src/constants/api.js
  frontend/src/store/atoms.js
Labels: 🕷 버그, ⭐⭐ 중요도

#289 fix: review cascadeType 제거
  src/main/java/com/main_39/Spring/review/entity/Review.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#290 fix: review, comment cascade 제거
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#291 fix: review 수정
  src/main/java/com/main_39/Spring/review/entity/Review.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#292 fix: commnet 삭제를 위한 review cascade 제거
  src/main/java/com/main_39/Spring/comment/entity/Comment.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#293 fix: review fetchtype 제거
  src/main/java/com/main_39/Spring/review/entity/Review.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#294 fix: review local 양방향
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#295 fix: reivew 수정
  src/main/java/com/main_39/Spring/review/entity/Review.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#296 fix: local 복원
  src/main/java/com/main_39/Spring/member/entity/Local.java
Labels: 🖥 BE, ⚙ 설정, 😎 유저 관련 작업

#297 fix: local 복원
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/store/dto/StoreResponseDto.java
Labels: 🖥 BE, ⚙ 설정, 😎 유저 관련 작업

#298 fix: store get URI 수정
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
Labels: 🖥 BE, ⚙ 설정, 🚚 푸드트럭 관련 작업

#299 fix: store get 복원
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
Labels: 🖥 BE, ⚙ 설정, 🚚 푸드트럭 관련 작업

#300 fix: deleteReview 수정
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#301 fix: deleteReview 수정
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#302 fix: deleteReview 수정
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#303 fix: deleteReview 수정
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#304 fix: review 수정
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#305 refactor: 엔티티 페치 타입 변경, batchSize 조절
  src/main/java/com/main_39/Spring/comment/entity/Comment.java
  src/main/java/com/main_39/Spring/member/entity/Kakao.java
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/menu/entity/Menu.java
  src/main/java/com/main_39/Spring/order/entity/Order.java
  src/main/java/com/main_39/Spring/order/entity/OrderMenu.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정

#306 fix : 엔티티 페치 타입 변경, batchSize 조절 revert
  src/main/java/com/main_39/Spring/comment/entity/Comment.java
  src/main/java/com/main_39/Spring/member/entity/Kakao.java
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/menu/entity/Menu.java
  src/main/java/com/main_39/Spring/order/entity/Order.java
  src/main/java/com/main_39/Spring/order/entity/OrderMenu.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정

#307 fix: review 수정
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/dto/ReviewPatchDto.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#308 fix: ReviewController 수정
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#309 fix: reviewController 복원
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/dto/ReviewPatchDto.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#310 fix: comment 수정
  src/main/java/com/main_39/Spring/comment/controller/CommentController.java
  src/main/java/com/main_39/Spring/comment/repository/CommentRepository.java
  src/main/java/com/main_39/Spring/comment/service/CommentService.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#311 fix: comment 수정 복원
  src/main/java/com/main_39/Spring/comment/controller/CommentController.java
  src/main/java/com/main_39/Spring/comment/repository/CommentRepository.java
  src/main/java/com/main_39/Spring/comment/service/CommentService.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#312 fix: comment 수정
  src/main/java/com/main_39/Spring/comment/controller/CommentController.java
  src/main/java/com/main_39/Spring/comment/entity/Comment.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#313 fix: comment 수정
  src/main/java/com/main_39/Spring/comment/controller/CommentController.java
  src/main/java/com/main_39/Spring/comment/entity/Comment.java
  src/main/java/com/main_39/Spring/comment/repository/CommentRepository.java
  src/main/java/com/main_39/Spring/comment/service/CommentService.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#314 fix: comment 수정
  src/main/java/com/main_39/Spring/comment/controller/CommentController.java
  src/main/java/com/main_39/Spring/comment/service/CommentService.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#315 fix: comment 복원
  src/main/java/com/main_39/Spring/comment/controller/CommentController.java
  src/main/java/com/main_39/Spring/comment/entity/Comment.java
  src/main/java/com/main_39/Spring/comment/repository/CommentRepository.java
  src/main/java/com/main_39/Spring/comment/service/CommentService.java
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#316 fix: reviewController delete 인증 삭제
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#317 feat: withAuth, MyPage naviate to trucksetting 기능 추가
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/Hoc/index.js
  frontend/src/constants/api.js
  frontend/src/constants/route.js
  frontend/src/hooks/useDetailFoodList.js
  frontend/src/hooks/useSetting.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/FoodTruckSetting/MenuList/index.js
  frontend/src/pages/FoodTruckSetting/UpdateForm/index.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/MyPage/index.js
  frontend/src/store/atoms.js
Labels: 📱 FE, 🔨 리펙토링, 🚚 푸드트럭 관련 작업

#318 feat: 스토어 수정 완료
  frontend/src/components/Answer/index.js
  frontend/src/constants/api.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/Login/ProviderLogin/index.js
  frontend/src/pages/Register/index.js
  frontend/src/store/atoms.js
Labels: 📱 FE, ⭐⭐ 중요도

#319 chore: 네트리파이 최종 배포 확인
  README.md
  frontend/src/components/Answer/index.js
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/Hoc/index.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/Login/ProviderLogin/index.js
  frontend/src/pages/Register/index.js
  frontend/src/store/atoms.js
Labels: 📱 FE, ⚙ 설정, ⭐⭐⭐ 중요도, 🌏 인프라

#320 refactor: 메뉴, 주문 엔티티 lazy
  src/main/java/com/main_39/Spring/menu/entity/Menu.java
  src/main/java/com/main_39/Spring/order/entity/Order.java
  src/main/java/com/main_39/Spring/order/entity/OrderMenu.java
Labels: 🖥 BE, ⚙ 설정

#323 fix: cascade 수정
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#324 fix: review 경로 수정
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#325 fix: S3이미지 저장관련 에러 수정
  src/main/java/com/main_39/Spring/menu/controller/MenuController.java
  src/main/java/com/main_39/Spring/menu/entity/Menu.java
  src/main/java/com/main_39/Spring/menu/service/MenuService.java
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🕷 버그, 🖥 BE

#328 fix: 2개이상의 가게 등록 금지
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🖥 BE, 🚚 푸드트럭 관련 작업

#329 fix: review, menu cascade 추가
  src/main/java/com/main_39/Spring/menu/entity/Menu.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정, 🙋‍♂️ 리뷰 관련 작업

#330 refactor: 리뷰 답변id 삭제 추가
  src/main/java/com/main_39/Spring/comment/service/CommentService.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
Labels: 🖥 BE, ⚙ 설정

#332 refactor: 가게 일대다 orphanRemoval 옵션추가
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정

#333 fix: orphanRemoval 옵션제거
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⚙ 설정

#336 refactor: 컴포넌트 텍스트 상수로 리펙토링 완료
  README.md
  frontend/src/components/DetailReview/index.js
  frontend/src/components/Hoc/index.js
  frontend/src/components/Receipt/index.js
  frontend/src/constants/api.js
  frontend/src/constants/text.js
  frontend/src/hooks/useAnswer.js
  frontend/src/hooks/useOrderList.js
  frontend/src/hooks/useReview.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/Login/LoginNav/index.js
  frontend/src/pages/Login/ProviderLogin/index.js
  frontend/src/pages/Login/styles.js
  frontend/src/pages/MyPage/index.js
  frontend/src/pages/Review/AskReview.js
  frontend/src/pages/Review/UpdateReview.js
  frontend/src/pages/Review/index.js
  frontend/src/store/storge.js
  server/app.js
Labels: 📱 FE, 🔨 리펙토링

#337 refactor: 컴포넌트 텍스트 상수로 리펙토링 완료
  README.md
  frontend/src/components/DetailReview/index.js
  frontend/src/components/Hoc/index.js
  frontend/src/components/Receipt/index.js
  frontend/src/constants/api.js
  frontend/src/constants/text.js
  frontend/src/hooks/useAnswer.js
  frontend/src/hooks/useOrderList.js
  frontend/src/hooks/useReview.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/Login/LoginNav/index.js
  frontend/src/pages/Login/ProviderLogin/index.js
  frontend/src/pages/Login/styles.js
  frontend/src/pages/MyPage/index.js
  frontend/src/pages/Review/AskReview.js
  frontend/src/pages/Review/UpdateReview.js
  frontend/src/pages/Review/index.js
  frontend/src/store/storge.js
  server/app.js
Labels: 📱 FE, 🔨 리펙토링

#338 refactor: 메뉴 dto, 서비스, 컨트롤러 리팩토링, 매퍼 인터페이스 -> 클래스 변환
  src/main/java/com/main_39/Spring/menu/MenuMapper.java
  src/main/java/com/main_39/Spring/menu/controller/MenuController.java
  src/main/java/com/main_39/Spring/menu/dto/MenuDetailResponse.java
  src/main/java/com/main_39/Spring/menu/dto/MenuResponse.java
  src/main/java/com/main_39/Spring/menu/dto/MenusResponse.java
  src/main/java/com/main_39/Spring/menu/mapper/MenuMapper.java
  src/main/java/com/main_39/Spring/menu/service/MenuService.java
Labels: 🖥 BE, 🔨 리펙토링

#339 fix: 메뉴 매퍼 @Component 추가
  src/main/java/com/main_39/Spring/menu/mapper/MenuMapper.java
Labels: 🖥 BE, ⚙ 설정

#341 refactor : config, member 패키지 리팩토링
  src/main/java/com/main_39/Spring/member/controller/MemberController.java
  src/main/java/com/main_39/Spring/member/dto/KakaoDto.java
  src/main/java/com/main_39/Spring/member/dto/LocalDto.java
  src/main/java/com/main_39/Spring/member/entity/Kakao.java
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/member/mapper/MemberMapper.java
  src/main/java/com/main_39/Spring/member/repository/KakaoRepository.java
  src/main/java/com/main_39/Spring/member/repository/LocalRepository.java
  src/main/java/com/main_39/Spring/member/service/MemberService.java
Labels: 🖥 BE, 🔨 리펙토링, 😎 유저 관련 작업, 🔒 인증 & 인가 관련 작업

#340 feat: 이미지 삽입 기능 추가 & CSS
  frontend/src/components/Hoc/index.js
  frontend/src/pages/FoodTruckSetting/MenuList/index.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/FoodTruckSetting/styles.js
  frontend/src/store/atoms.js
Labels: 📱 FE, ✨ UI/UX, 🚚 푸드트럭 관련 작업

#343 feat: 오류처리 추가, UX개선
  frontend/src/pages/FoodTruckSetting/UpdateForm/index.js
  frontend/src/pages/FoodTruckSetting/index.js
Labels: 📱 FE, ✨ UI/UX, 🚚 푸드트럭 관련 작업

#345 fix: url 수정 완료
  frontend/src/App.js
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/FoodTruck/index.js
  frontend/src/components/Receipt/index.js
  frontend/src/components/Thumbnail/index.js
  frontend/src/constants/text.js
  frontend/src/hooks/useOrderList.js
  frontend/src/hooks/usePay.js
  frontend/src/pages/Basket/index.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/FoodList/FoodDetail/styles.js
  frontend/src/pages/Login/ProviderLogin/index.js
  frontend/src/pages/MyPage/index.js
  frontend/src/pages/MyPage/styles.js
  frontend/src/pages/NotFound/index.js
  frontend/src/pages/Order/index.js
  frontend/src/pages/PwChange/index.js
  frontend/src/pages/PwInquiry/index.js
  frontend/src/pages/Register/index.js
  frontend/src/pages/Review/AskReview.js
Labels: ⚙ 설정

#346 fix: 비회원 주문 시 예외처리 추가
  src/main/java/com/main_39/Spring/order/controller/OrderController.java
Labels: 🖥 BE, ⚙ 설정

#347 feat: 메뉴수정 UX 개선
  frontend/src/pages/FoodTruckSetting/MenuList/index.js
Labels: 📱 FE, ✨ UI/UX, 🚚 푸드트럭 관련 작업

#348 design: 이미지 파일 수정 완료
  frontend/src/components/CustomModal/FoodModal/index.js
  frontend/src/components/CustomModal/FoodModal/styles.js
  frontend/src/components/Receipt/index.js
  frontend/src/hooks/useOrderList.js
  frontend/src/pages/Review/AskReview.js
  frontend/src/pages/Review/UpdateReview.js
  frontend/src/pages/Review/styles.js
Labels: ⚙ 설정, ✨ UI/UX, ⭐⭐ 중요도

#349 feat: 가게설정 UX 개선
  frontend/src/pages/FoodTruckSetting/MenuList/index.js
  frontend/src/pages/FoodTruckSetting/UpdateForm/index.js
  frontend/src/pages/FoodTruckSetting/index.js
Labels: 📱 FE, ✨ UI/UX, 🚚 푸드트럭 관련 작업
