Repository codestates-seb/seb39_main_038, pull requests merged in 2022-09, with the labels that each got.

#2 ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
Labels: 📃 문서, ⚙ 설정

#3 feat: 프론트엔드 기본 설정 완료
  .gitignore
  LICENSE
  frontend/.eslintrc.json
  frontend/.husky/pre-commit
  frontend/.prettierrc.json
  frontend/babel.config.js
  frontend/netlify.toml
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/webpack.config.js
  server/app.js
  server/package-lock.json
  server/package.json
Labels: 📱 FE, ⚙ 설정, ⭐⭐⭐ 중요도

#5 docs: 노션 링크 추가 완료
  README.md
Labels: 📃 문서

#10 feat: 백엔드 초기설정
  Spring/.gitignore
  Spring/build.gradle
  Spring/gradle/wrapper/gradle-wrapper.jar
  Spring/gradle/wrapper/gradle-wrapper.properties
  Spring/gradlew
  Spring/gradlew.bat
  Spring/settings.gradle
  Spring/src/main/java/com/main_39/Spring/Application.java
  Spring/src/main/java/com/main_39/Spring/advice/ErrorResponse.java
  Spring/src/main/java/com/main_39/Spring/advice/GlobalExceptionAdvice.java
  Spring/src/main/java/com/main_39/Spring/audit/Auditable.java
  Spring/src/main/java/com/main_39/Spring/dto/MultiResponseDto.java
  Spring/src/main/java/com/main_39/Spring/dto/PageInfo.java
  Spring/src/main/java/com/main_39/Spring/dto/SingleResponseDto.java
  Spring/src/main/java/com/main_39/Spring/exception/BusinessLogicException.java
  Spring/src/main/java/com/main_39/Spring/exception/ExceptionCode.java
  Spring/src/main/resources/application.properties
  Spring/src/test/java/com/main_39/Spring/ApplicationTests.java
Labels: 🖥 BE, ⚙ 설정, ⭐⭐ 중요도

#11 feat: 백엔드 초기설정
  Spring/.gitignore
  Spring/build.gradle
  Spring/gradle/wrapper/gradle-wrapper.jar
  Spring/gradle/wrapper/gradle-wrapper.properties
  Spring/gradlew
  Spring/gradlew.bat
  Spring/settings.gradle
  Spring/src/main/java/com/main_39/Spring/Application.java
  Spring/src/main/java/com/main_39/Spring/advice/ErrorResponse.java
  Spring/src/main/java/com/main_39/Spring/advice/GlobalExceptionAdvice.java
  Spring/src/main/java/com/main_39/Spring/audit/Auditable.java
  Spring/src/main/java/com/main_39/Spring/dto/MultiResponseDto.java
  Spring/src/main/java/com/main_39/Spring/dto/PageInfo.java
  Spring/src/main/java/com/main_39/Spring/dto/SingleResponseDto.java
  Spring/src/main/java/com/main_39/Spring/exception/BusinessLogicException.java
  Spring/src/main/java/com/main_39/Spring/exception/ExceptionCode.java
  Spring/src/main/resources/application.properties
  Spring/src/test/java/com/main_39/Spring/ApplicationTests.java
Labels: 🖥 BE, ⚙ 설정, ⭐⭐⭐ 중요도

#12 feat: dev/aws branch aws 설정
  .github/workflows/gradle.yml
  .gitignore
  appspec.yml
  backend/.gitignore
  build.gradle
  buildspec.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  scripts/deploy.sh
  scripts/initialize.sh
  scripts/server_clear.sh
  scripts/server_start.sh
  scripts/server_stop.sh
  settings.gradle
  src/main/java/com/main_39/Spring/Application.java
  src/main/java/com/main_39/Spring/advice/ErrorResponse.java
  src/main/java/com/main_39/Spring/advice/GlobalExceptionAdvice.java
  src/main/java/com/main_39/Spring/audit/Auditable.java
  src/main/java/com/main_39/Spring/dto/MultiResponseDto.java
  src/main/java/com/main_39/Spring/dto/PageInfo.java
  src/main/java/com/main_39/Spring/dto/SingleResponseDto.java
  src/main/java/com/main_39/Spring/exception/BusinessLogicException.java
  src/main/java/com/main_39/Spring/exception/ExceptionCode.java
  src/main/resources/application.properties
  src/test/java/com/main_39/Spring/ApplicationTests.java
Labels: 🖥 BE, ⚙ 설정

#20 feat: CSRF, CORS 설정 허용
  src/main/java/com/main_39/Spring/config/CorsConfig.java
  src/main/java/com/main_39/Spring/config/SecurityConfig.java
  src/main/java/com/main_39/Spring/member/controller/MemberController.java
  src/main/java/com/main_39/Spring/member/dto/MemberDto.java
  src/main/java/com/main_39/Spring/member/entity/Kakao.java
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/member/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🖥 BE, ⚙ 설정

#22 docs: 노션 링크 추가 완료
  README.md
Labels: 📃 문서

#35 chore: 네트리파이 배포 완료
  frontend/public/index.html
  frontend/public/logo.png
  frontend/webpack.config.js
Labels: 📱 FE, ⚙ 설정

#42 feat: crud 테스트를 위한 PR
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  src/main/java/com/main_39/Spring/test/TestController.java
  src/main/java/com/main_39/Spring/test/TestService.java
  src/main/java/com/main_39/Spring/test/domain/Test.java
  src/main/java/com/main_39/Spring/test/domain/TestRepository.java
  src/main/java/com/main_39/Spring/test/dto/PatchRequestDto.java
  src/main/java/com/main_39/Spring/test/dto/PostRequestDto.java
  src/main/resources/application.yml
  src/test/java/com/main_39/Spring/ApiTest.http
Labels: 🖥 BE, ⚙ 설정

#43 feat : crud test를 위한 PR
  .github/workflows/gradle.yml
Labels: 🖥 BE, ⚙ 설정

#45 feat: crud test를 위한 PR
  test
Labels: 🖥 BE, ⚙ 설정

#47 feat: CRUD 테스트를 위한 PR
  PR
Labels: 🖥 BE, ⚙ 설정

#48 feat: crud test를 위한 PR
  build.gradle
Labels: 🖥 BE, ⚙ 설정

#49 feat: OAuth2.0 카카오 로그인 추가
  build.gradle
  src/main/java/com/main_39/Spring/config/SecurityConfig.java
  src/main/java/com/main_39/Spring/config/WebMvcConfig.java
  src/main/java/com/main_39/Spring/config/filter/JwtAuthorizationFilter.java
  src/main/java/com/main_39/Spring/config/oauth/KakaoOAuth2UserService.java
  src/main/java/com/main_39/Spring/config/oauth/MyOAuth2SuccessHandler.java
  src/main/java/com/main_39/Spring/config/oauth/PrincipalDetails.java
  src/main/java/com/main_39/Spring/exception/ExceptionCode.java
  src/main/java/com/main_39/Spring/member/controller/MemberController.java
  src/main/java/com/main_39/Spring/member/dto/CodeDto.java
  src/main/java/com/main_39/Spring/member/dto/KakaoProfile.java
  src/main/java/com/main_39/Spring/member/dto/LocalDto.java
  src/main/java/com/main_39/Spring/member/dto/MemberDto.java
  src/main/java/com/main_39/Spring/member/dto/OAuthToken.java
  src/main/java/com/main_39/Spring/member/entity/Kakao.java
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/member/mapper/MemberMapper.java
  src/main/java/com/main_39/Spring/member/repository/KakaoRepository.java
  src/main/java/com/main_39/Spring/member/repository/LocalRepository.java
  src/main/java/com/main_39/Spring/member/service/MemberService.java
  src/main/resources/static/image/kakao_login_medium_wide.png
  src/main/resources/templates/loginForm.html
Labels: 🖥 BE, ⭐ 중요도

#57 feat: GlobalNav 컴포넌트 & Login 페이지 구현 완료
  README.md
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/GlobalNav/index.js
  frontend/src/components/GlobalNav/styles.js
  frontend/src/constants/api.js
  frontend/src/constants/color.js
  frontend/src/constants/index.js
  frontend/src/constants/route.js
  frontend/src/constants/screen.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/pages/Basket/index.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/Login/styles.js
  frontend/webpack.config.js
Labels: 📱 FE, 📃 문서, ⚙ 설정, ✨ UI/UX, ⭐ 중요도, 😎 유저 관련 작업

#58 feat: GlobalNav 컴포넌트 & Login 페이지 구현 완료
  .gitignore
  README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/logo.png
  frontend/src/App.js
  frontend/src/components/GlobalNav/index.js
  frontend/src/components/GlobalNav/styles.js
  frontend/src/components/Spinner/index.js
  frontend/src/components/Spinner/styles.js
  frontend/src/constants/api.js
  frontend/src/constants/color.js
  frontend/src/constants/index.js
  frontend/src/constants/route.js
  frontend/src/constants/screen.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/pages/Basket/index.js
  frontend/src/pages/FoodList/index.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/IdInquiry/index.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/Login/styles.js
  frontend/src/pages/PwInquiry/index.js
  frontend/src/pages/Register/index.js
  frontend/webpack.config.js
Labels: 📱 FE, 📃 문서, ⚙ 설정, ✨ UI/UX, ⭐⭐ 중요도, 😎 유저 관련 작업

#62 feat: crud test를 위한 PR
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  build.gradle_bk
Labels: 🖥 BE, ⚙ 설정

#60 design: FoodDetail 모바일 CSS 구성 완료
  frontend/src/components/DetailMenuBar/index.js
  frontend/src/index.js
  frontend/src/pages/FoodList/Detailstyles.js
  frontend/src/pages/FoodList/FoodDetail.js
  frontend/src/pages/FoodList/index.js
  frontend/src/style/theme.js
Labels: 📱 FE, ✨ UI/UX

#64 fix: build.gradle 수정
  build.gradle
  src/main/java/com/main_39/Spring/config/filter/JwtAuthorizationFilter.java
  src/main/java/com/main_39/Spring/config/filter/Valid.java
  src/main/java/com/main_39/Spring/exception/ExceptionCode.java
  src/main/java/com/main_39/Spring/member/controller/MemberController.java
  src/main/java/com/main_39/Spring/member/dto/CodeDto.java
  src/main/java/com/main_39/Spring/member/service/MemberService.java
Labels: 🖥 BE, ⚙ 설정

#68 design: Home 컴포넌트 UI & CSS 구현 완료
  frontend/src/components/Form/index.js
  frontend/src/components/LocalNav/index.js
  frontend/src/components/Thumbnail/index.js
  frontend/src/components/Thumbnail/styles.js
  frontend/src/constants/route.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/styles.js
  frontend/src/pages/IdInquiry/index.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/PwInquiry/index.js
Labels: 📱 FE, ✨ UI/UX

#69 design: Home 컴포넌트 UI & CSS 구현 완료
  frontend/src/components/Banner/index.js
  frontend/src/components/LocalNav/index.js
  frontend/src/components/LocalNav/styles.js
  frontend/src/components/Thumbnail/index.js
  frontend/src/constants/index.js
  frontend/src/constants/menu.js
  frontend/src/pages/FoodList/index.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/styles.js
  frontend/src/pages/Register/index.js
Labels: 📱 FE, ✨ UI/UX, ⭐ 중요도

#70 fix: 중괄호 누락 수정 완료
  frontend/src/components/LocalNav/index.js
Labels: 🕷 버그, 📱 FE

#71 Design: FoodDetail 클린리뷰 CSS 구성 완료
  frontend/src/components/DetailMenuBar/atom.js
  frontend/src/components/DetailMenuBar/index.js
  frontend/src/components/DetailMenuBar/styles.js
  frontend/src/index.js
  frontend/src/pages/FoodList/Detailstyles.js
  frontend/src/pages/FoodList/FoodDetail.js
  frontend/src/style/theme.js
Labels: 📱 FE, ✨ UI/UX

#75 Design: FoodDetail 페이지 CSS 구성 완료
  frontend/src/components/DetailMenuBar/atom.js
  frontend/src/components/DetailMenuBar/index.js
  frontend/src/components/DetailMenuBar/styles.js
  frontend/src/pages/FoodList/FoodDetail.js
  frontend/src/pages/FoodList/FoodDetailstyles.js
Labels: 📱 FE, ✨ UI/UX

#77 feat: FoodList 컴포넌트 구현 완료
  frontend/src/App.js
  frontend/src/components/FoodTruck/index.js
  frontend/src/components/FoodTruck/styles.js
  frontend/src/components/Form/index.js
  frontend/src/components/GlobalNav/index.js
  frontend/src/components/LocalNav/index.js
  frontend/src/components/Spinner/index.js
  frontend/src/components/Thumbnail/index.js
  frontend/src/components/index.js
  frontend/src/pages/FoodList/FoodTrucks.js
  frontend/src/pages/FoodList/index.js
  frontend/src/pages/FoodList/styles.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/IdInquiry/index.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/Login/styles.js
  frontend/src/pages/PwInquiry/index.js
  frontend/src/pages/Register/index.js
Labels: 📱 FE, ✨ UI/UX

#78 design: Modal 컴포넌트 UI & CSS 구현 완료
  frontend/public/index.html
  frontend/src/components/FoodTruck/index.js
  frontend/src/components/LocalNav/index.js
  frontend/src/components/Modal/index.js
  frontend/src/components/Modal/styles.js
  frontend/src/constants/route.js
  frontend/src/pages/FoodList/index.js
  frontend/src/pages/Home/index.js
  frontend/src/store/atoms.js
  frontend/src/store/index.js
Labels: 📱 FE, ✨ UI/UX, 🔨 리펙토링

#79 feat: 주문표 Receipt 컴포넌트화 완료
  frontend/atom/index.js
  frontend/src/components/DetailFoodMenu/index.js
  frontend/src/components/DetailFoodMenu/styles.js
  frontend/src/components/DetailInfo/index.js
  frontend/src/components/DetailInfo/styles.js
  frontend/src/components/DetailMenuBar/atom.js
  frontend/src/components/DetailMenuBar/index.js
  frontend/src/components/DetailMenuBar/styles.js
  frontend/src/components/DetailReview/index.js
  frontend/src/components/DetailReview/styles.js
  frontend/src/components/Receipt/index.js
  frontend/src/components/Receipt/styles.js
  frontend/src/components/index.js
  frontend/src/pages/FoodList/FoodDetail.js
  frontend/src/pages/FoodList/styles.js
Labels: 📱 FE, ✨ UI/UX, 🔨 리펙토링

#83 feat: 모달 테스트 인터페이스 제공 완료
  frontend/src/components/Modal/EmailModal.js
  frontend/src/components/Modal/FoodModal.js
  frontend/src/components/Modal/Modal.js
  frontend/src/components/Modal/OrderModal.js
  frontend/src/components/Modal/index.js
  frontend/src/components/Modal/styles.js
  frontend/src/components/index.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useModal.js
  frontend/src/pages/Home/index.js
  frontend/src/store/atoms.js
Labels: 🕷 버그, ✨ UI/UX

#76 refactor: 주문 dto -> 엔티티 변환 구현
  build.gradle
  src/main/java/com/main_39/Spring/member/entity/Kakao.java
  src/main/java/com/main_39/Spring/menu/Menu.java
  src/main/java/com/main_39/Spring/order/controller/OrderController.java
  src/main/java/com/main_39/Spring/order/controller/dto/OrderMenuPostRequestDto.java
  src/main/java/com/main_39/Spring/order/controller/dto/OrderMenuResponseDto.java
  src/main/java/com/main_39/Spring/order/controller/dto/OrderPostRequestDto.java
  src/main/java/com/main_39/Spring/order/controller/dto/OrderResponseDto.java
  src/main/java/com/main_39/Spring/order/entity/Order.java
  src/main/java/com/main_39/Spring/order/entity/OrderMenu.java
  src/main/java/com/main_39/Spring/order/mapper/OrderMapper.java
  src/main/java/com/main_39/Spring/order/repository/OrderRepository.java
  src/main/java/com/main_39/Spring/order/service/OrderService.java
  src/test/java/com/main_39/Spring/ApiTest.http
Labels: 🖥 BE, 🔨 리펙토링, 💾 데이터 베이스

#86 Design: FoodDetail CSS 추가 작업 완료
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/DetailFoodList/styles.js
  frontend/src/components/DetailInfo/index.js
  frontend/src/components/DetailInfo/styles.js
  frontend/src/components/DetailMenuBar/atom.js
  frontend/src/components/DetailMenuBar/index.js
  frontend/src/components/DetailMenuBar/styles.js
  frontend/src/components/DetailReview/index.js
  frontend/src/components/DetailReview/styles.js
  frontend/src/components/LocalNav/styles.js
  frontend/src/components/Receipt/index.js
  frontend/src/components/Receipt/styles.js
  frontend/src/components/index.js
  frontend/src/index.js
  frontend/src/pages/FoodList/FoodDetail.js
  frontend/src/pages/FoodList/styles.js
  frontend/src/store/atoms.js
  frontend/src/store/index.js
  frontend/src/store/theme.js
Labels: 📱 FE, ✨ UI/UX, 🔨 리펙토링

#88 feat: 멤버 회원가입 로그인 로그아웃, 카카오 로그아웃, 쿠키 통신 추가
  src/main/java/com/main_39/Spring/config/CorsConfig.java
  src/main/java/com/main_39/Spring/config/SecurityConfig.java
  src/main/java/com/main_39/Spring/config/filter/JwtAuthenticationFilter.java
  src/main/java/com/main_39/Spring/config/filter/JwtAuthorizationFilter.java
  src/main/java/com/main_39/Spring/config/filter/Valid.java
  src/main/java/com/main_39/Spring/config/oauth/KakaoDetails.java
  src/main/java/com/main_39/Spring/config/oauth/KakaoOAuth2UserService.java
  src/main/java/com/main_39/Spring/config/oauth/LocalDetails.java
  src/main/java/com/main_39/Spring/config/oauth/LocalDetailsService.java
  src/main/java/com/main_39/Spring/config/oauth/MyOAuth2SuccessHandler.java
  src/main/java/com/main_39/Spring/member/controller/MemberController.java
  src/main/java/com/main_39/Spring/member/dto/CodeDto.java
  src/main/java/com/main_39/Spring/member/dto/KakaoDto.java
  src/main/java/com/main_39/Spring/member/dto/LocalDto.java
  src/main/java/com/main_39/Spring/member/entity/Kakao.java
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/member/mapper/MemberMapper.java
  src/main/java/com/main_39/Spring/member/repository/LocalRepository.java
  src/main/java/com/main_39/Spring/member/service/MemberService.java
Labels: 🖥 BE, ⭐ 중요도

#89 refactor: CustomModal & FoodList 컴포넌트 모듈화 완료
  frontend/src/components/CustomModal/EmailModal/index.js
  frontend/src/components/CustomModal/EmailModal/styles.js
  frontend/src/components/CustomModal/FoodModal/index.js
  frontend/src/components/CustomModal/FoodModal/styles.js
  frontend/src/components/CustomModal/Modal/index.js
  frontend/src/components/CustomModal/Modal/styles.js
  frontend/src/components/CustomModal/OrderModal/index.js
  frontend/src/components/CustomModal/OrderModal/styles.js
  frontend/src/components/CustomModal/index.js
  frontend/src/components/Modal/styles.js
  frontend/src/components/index.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/FoodList/FoodDetail/styles.js
  frontend/src/pages/FoodList/FoodDetailstyles.js
  frontend/src/pages/FoodList/FoodTrucks/index.js
  frontend/src/pages/FoodList/FoodTrucks/styles.js
  frontend/src/pages/Home/index.js
Labels: 📱 FE, 🔨 리펙토링

#90 Design: 가게설정 페이지 CSS 완료
  frontend/src/App.js
  frontend/src/components/Receipt/index.js
  frontend/src/components/Receipt/styles.js
  frontend/src/components/ReceiptList/index.js
  frontend/src/components/ReceiptList/styles.js
  frontend/src/constants/route.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/FoodList/FoodDetail/styles.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/FoodTruckSetting/styles.js
Labels: 📱 FE, ✨ UI/UX, 🔨 리펙토링

#91 feat: Order & NotFound UI & CSS 구현 완료
  frontend/src/App.js
  frontend/src/constants/route.js
  frontend/src/index.css
  frontend/src/pages/MyPage/index.js
  frontend/src/pages/NotFound/index.js
  frontend/src/pages/NotFound/styles.js
  frontend/src/pages/Order/index.js
  frontend/src/pages/Order/styles.js
Labels: 📱 FE, ✨ UI/UX

#92 design: MyPage 컴포넌트 목업 완료
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/constants/route.js
  frontend/src/pages/MyPage/index.js
  frontend/webpack.config.js
Labels: ⚙ 설정, ✨ UI/UX

#94 feat: 이메일 찾기, 비밀번호 찾기, 회원 마이페이지 기능 추가
  src/main/java/com/main_39/Spring/config/CorsConfig.java
  src/main/java/com/main_39/Spring/config/filter/JwtAuthenticationFilter.java
  src/main/java/com/main_39/Spring/member/controller/MemberController.java
  src/main/java/com/main_39/Spring/member/dto/KakaoDto.java
  src/main/java/com/main_39/Spring/member/dto/LocalDto.java
  src/main/java/com/main_39/Spring/member/entity/Kakao.java
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/member/mapper/MemberMapper.java
  src/main/java/com/main_39/Spring/member/repository/LocalRepository.java
  src/main/java/com/main_39/Spring/member/service/MemberService.java
  src/main/java/com/main_39/Spring/store/dto/StoreDto.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
Labels: 🖥 BE, ⭐ 중요도

#113 feat: 통신코드 작업중 & 태그 인풋 CSS 작업중
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/Receipt/index.js
  frontend/src/components/ReceiptList/index.js
  frontend/src/pages/FoodList/FoodDetail/styles.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/FoodTruckSetting/styles.js
  frontend/src/store/atoms.js
  frontend/webpack.config.js
Labels: 📱 FE, ✨ UI/UX

#116 rename: 프론트엔드와의 JSON 필드명 맞춤
  src/main/java/com/main_39/Spring/config/filter/JwtAuthenticationFilter.java
  src/main/java/com/main_39/Spring/config/filter/JwtAuthorizationFilter.java
  src/main/java/com/main_39/Spring/config/filter/Valid.java
  src/main/java/com/main_39/Spring/config/oauth/LocalDetails.java
  src/main/java/com/main_39/Spring/config/oauth/LocalDetailsService.java
  src/main/java/com/main_39/Spring/member/controller/MemberController.java
  src/main/java/com/main_39/Spring/member/dto/LocalDto.java
  src/main/java/com/main_39/Spring/member/entity/Local.java
  src/main/java/com/main_39/Spring/member/mapper/MemberMapper.java
  src/main/java/com/main_39/Spring/member/repository/LocalRepository.java
  src/main/java/com/main_39/Spring/member/service/MemberService.java
Labels: 🖥 BE, ⭐ 중요도

#117 fix: 통신 테스트
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/FoodTruckSetting/styles.js
  frontend/src/store/atoms.js
Labels: 📱 FE

#119 feat: 회원가입 로직 구현 완료
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/Form/index.js
  frontend/src/components/GlobalNav/index.js
  frontend/src/components/LocalNav/index.js
  frontend/src/components/LocalNav/styles.js
  frontend/src/components/SvgIcon/index.js
  frontend/src/components/index.js
  frontend/src/constants/alert.js
  frontend/src/constants/api.js
  frontend/src/constants/index.js
  frontend/src/constants/menu.js
  frontend/src/constants/text.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/IdInquiry/index.js
  frontend/src/pages/Login/ConsumerLogin/index.js
  frontend/src/pages/Login/ConsumerLogin/styles.js
  frontend/src/pages/Login/LoginNav/index.js
  frontend/src/pages/Login/LoginNav/styles.js
  frontend/src/pages/Login/ProviderLogin/index.js
  frontend/src/pages/Login/ProviderLogin/styles.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/PwInquiry/index.js
  frontend/src/pages/PwInquiry/styles.js
  frontend/src/pages/Register/index.js
  frontend/src/utils/index.js
  frontend/src/utils/sha256.js
  frontend/webpack.config.js
Labels: 📱 FE, ⭐ 중요도, 🔨 리펙토링, 😎 유저 관련 작업

#134 fix: 로그인 경로 수정 완료
  frontend/src/constants/api.js
  frontend/src/pages/Login/ProviderLogin/index.js
  frontend/src/pages/Register/index.js
Labels: 📱 FE, ⭐ 중요도, 😎 유저 관련 작업

#136 feat: store, review merge
  src/main/java/com/main_39/Spring/advice/ErrorResponse.java
  src/main/java/com/main_39/Spring/exception/ExceptionCode.java
  src/main/java/com/main_39/Spring/member/dto/LocalDto.java
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/review/dto/ReviewPatchDto.java
  src/main/java/com/main_39/Spring/review/dto/ReviewPostDto.java
  src/main/java/com/main_39/Spring/review/dto/ReviewResponseDto.java
  src/main/java/com/main_39/Spring/review/entity/Review.java
  src/main/java/com/main_39/Spring/review/entity/ReviewSeller.java
  src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
  src/main/java/com/main_39/Spring/review/repository/ReviewRepository.java
  src/main/java/com/main_39/Spring/review/service/ReviewService.java
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
  src/main/java/com/main_39/Spring/store/dto/StoreMenuPostDto.java
  src/main/java/com/main_39/Spring/store/dto/StoreMenuResponseDto.java
  src/main/java/com/main_39/Spring/store/dto/StorePatchDto.java
  src/main/java/com/main_39/Spring/store/dto/StorePostDto.java
  src/main/java/com/main_39/Spring/store/dto/StoreResponseDto.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
  src/main/java/com/main_39/Spring/store/mapper/StoreMapper.java
  src/main/java/com/main_39/Spring/store/repository/StoreRepository.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
  src/main/resources/application-local.yml
  src/main/resources/application-server.yml
Labels: 🖥 BE, ⚙ 설정

#135 feat: ThemeProvider 제거, 디테일 메뉴탭 분기처리 리액트 쿼리 완료
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/DetailFoodList/styles.js
  frontend/src/components/DetailReview/styles.js
  frontend/src/components/Receipt/index.js
  frontend/src/components/Receipt/styles.js
  frontend/src/index.js
  frontend/src/pages/FoodList/FoodDetail/styles.js
  frontend/src/pages/FoodTruckSetting/styles.js
  frontend/src/store/atoms.js
  frontend/src/store/index.js
  frontend/src/store/theme.js
Labels: 📱 FE, ⚙ 설정, ✨ UI/UX, 🔨 리펙토링

#137 feat: 비밀번호 찾기 시 이메일 인증코드 확인 기능 추가
  build.gradle
  src/main/java/com/main_39/Spring/config/SecurityConfig.java
  src/main/java/com/main_39/Spring/config/filter/JwtAuthenticationFilter.java
  src/main/java/com/main_39/Spring/member/controller/MemberController.java
  src/main/java/com/main_39/Spring/member/dto/KakaoDto.java
  src/main/java/com/main_39/Spring/member/dto/LocalDto.java
  src/main/java/com/main_39/Spring/member/mapper/MemberMapper.java
  src/main/java/com/main_39/Spring/member/repository/LocalRepository.java
  src/main/java/com/main_39/Spring/member/service/MemberService.java
  src/main/java/com/main_39/Spring/menu/service/MenuService.java
Labels: 🖥 BE, ⭐ 중요도

#138 design: MyPage 컴포넌트 UI & CSS 구현완료
  frontend/src/pages/MyPage/index.js
  frontend/src/pages/MyPage/styles.js
Labels: 📱 FE, ✨ UI/UX

#150 feat: 로그인 세션 유지 기능 완료
  frontend/src/App.js
  frontend/src/components/CustomModal/EmailModal/index.js
  frontend/src/components/GlobalNav/index.js
  frontend/src/constants/alert.js
  frontend/src/constants/api.js
  frontend/src/constants/route.js
  frontend/src/index.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/styles.js
  frontend/src/pages/IdInquiry/index.js
  frontend/src/pages/Login/ProviderLogin/index.js
  frontend/src/pages/MyPage/index.js
  frontend/src/pages/PwChange/index.js
  frontend/src/pages/PwInquiry/index.js
  frontend/src/pages/Register/index.js
  frontend/src/store/atoms.js
  frontend/src/store/index.js
  frontend/src/store/storge.js
Labels: 📱 FE, ✨ UI/UX, ⭐⭐ 중요도

#155 feat: s3 이미지 업로드
  build.gradle
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
  src/main/java/com/main_39/Spring/store/repository/StoreRepository.java
  src/main/java/com/main_39/Spring/store/service/S3Uploader.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🖥 BE, ⚙ 설정

#156 feat: aws image 업로드 복원
  build.gradle
  src/main/java/com/main_39/Spring/review/controller/ReviewController.java
  src/main/java/com/main_39/Spring/store/controller/StoreController.java
  src/main/java/com/main_39/Spring/store/entity/Store.java
  src/main/java/com/main_39/Spring/store/repository/StoreRepository.java
  src/main/java/com/main_39/Spring/store/service/S3Uploader.java
  src/main/java/com/main_39/Spring/store/service/StoreService.java
Labels: 🖥 BE, ⚙ 설정

#151 feat: 로그인 기능 & 로그인 세션 유지 구현 완료
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/CustomModal/EmailModal/index.js
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/DetailFoodList/styles.js
  frontend/src/components/DetailReview/styles.js
  frontend/src/components/Form/index.js
  frontend/src/components/GlobalNav/index.js
  frontend/src/components/LocalNav/index.js
  frontend/src/components/LocalNav/styles.js
  frontend/src/components/Receipt/index.js
  frontend/src/components/Receipt/styles.js
  frontend/src/components/ReceiptList/index.js
  frontend/src/components/SvgIcon/index.js
  frontend/src/components/index.js
  frontend/src/constants/alert.js
  frontend/src/constants/api.js
  frontend/src/constants/index.js
  frontend/src/constants/menu.js
  frontend/src/constants/route.js
  frontend/src/constants/text.js
  frontend/src/index.js
  frontend/src/pages/FoodList/FoodDetail/styles.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/FoodTruckSetting/styles.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/styles.js
  frontend/src/pages/IdInquiry/index.js
  frontend/src/pages/Login/ConsumerLogin/index.js
  frontend/src/pages/Login/ConsumerLogin/styles.js
  frontend/src/pages/Login/LoginNav/index.js
  frontend/src/pages/Login/LoginNav/styles.js
  frontend/src/pages/Login/ProviderLogin/index.js
  frontend/src/pages/Login/ProviderLogin/styles.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/Login/styles.js
  frontend/src/pages/MyPage/index.js
  frontend/src/pages/MyPage/styles.js
  frontend/src/pages/PwChange/index.js
  frontend/src/pages/PwInquiry/index.js
  frontend/src/pages/PwInquiry/styles.js
  frontend/src/pages/Register/index.js
  frontend/src/store/atoms.js
  frontend/src/store/index.js
  frontend/src/store/storge.js
  frontend/src/utils/index.js
  frontend/src/utils/sha256.js
  frontend/webpack.config.js
Labels: 📱 FE, ⭐⭐ 중요도, 🔨 리펙토링, 😎 유저 관련 작업

#153 feat: CRUD 가게페이지 완료, Detail 구성중 & 가게페이지 드랍다운 완성
  frontend/src/components/DetailFoodList/index.js
  frontend/src/components/DetailInfo/index.js
  frontend/src/components/DetailReview/index.js
  frontend/src/components/Receipt/styles.js
  frontend/src/constants/route.js
  frontend/src/index.js
  frontend/src/pages/FoodList/FoodDetail/index.js
  frontend/src/pages/FoodList/FoodDetail/styles.js
  frontend/src/pages/FoodTruckSetting/index.js
  frontend/src/pages/FoodTruckSetting/styles.js
  frontend/src/store/atoms.js
  frontend/src/store/index.js
  frontend/src/store/theme.js
Labels: 🕷 버그, 📱 FE, ✨ UI/UX, ⭐⭐ 중요도

#161 feat: 푸드트럭 페이지 서버와 연동 완료
  frontend/src/components/FoodTruck/index.js
  frontend/src/components/LocalNav/index.js
  frontend/src/constants/api.js
  frontend/src/index.js
  frontend/src/pages/FoodList/FoodTrucks/index.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/MyPage/index.js
  frontend/src/pages/Order/index.js
  frontend/src/pages/Order/styles.js
  frontend/src/pages/PwChange/index.js
  frontend/src/store/atoms.js
  frontend/src/store/index.js
  server/app.js
  server/data/foodList.js
  server/data/index.js
  server/utils/index.js
Labels: 📱 FE, ⭐ 중요도
